-- ============================================================
-- CafeTrack — schema updates to apply to a hosted project
-- Generated by: npm run db:migrate  (do not edit by hand)
-- Source:      db/schema.sql
-- Generated:   2026-09-28
-- ============================================================
--
-- HOW TO USE
--   Supabase dashboard -> SQL Editor -> New query -> paste this whole file
--   -> Run. It is safe to run more than once.
--
-- What this contains: only the re-runnable statements, so it cannot create,
-- drop, or modify any client data. Tables, indexes, the extension, the default
-- settings rows, and the row-level security statements are all excluded on
-- purpose — they are set up once when the project is created and are not
-- needed to pick up a change to a stored function.
--
-- Apply a structural change (a new table, column, or index) by running the
-- full db/schema.sql in the SQL Editor instead. That file is also re-runnable
-- and never drops or truncates anything.
--

-- ---------- columns added since the first release ----------
-- Safe on a live database: the column is added only if it is not already there,
-- and existing rows are left untouched.
alter table users add column if not exists deactivation_reason text;
alter table users add column if not exists deactivated_at timestamptz;

-- ---------- stored functions ----------
-- create or replace keeps the existing function id and re-points it at the new
-- body, so anything already calling it keeps working.
-- append_audit()
create or replace function append_audit(
  p_actor_id    uuid,
  p_actor_name  text,
  p_action      text,
  p_entity_type text,
  p_entity_id   text,
  p_details     jsonb
) returns audit_log
language plpgsql
security definer
as $$
declare
  v_prev  text;
  v_row   audit_log;
  v_hash  text;
begin
  -- serialize writers so the chain can't fork
  lock table audit_log in exclusive mode;

  select entry_hash into v_prev from audit_log order by seq desc limit 1;
  v_prev := coalesce(v_prev, 'GENESIS');

  insert into audit_log (actor_id, actor_name, action, entity_type, entity_id, details, prev_hash, entry_hash)
  values (p_actor_id, p_actor_name, p_action, p_entity_type, p_entity_id,
          coalesce(p_details, '{}'::jsonb), v_prev, '')
  returning * into v_row;

  v_hash := encode(digest(
      v_row.seq::text || '|' || v_prev || '|' || p_actor_name || '|' || p_action || '|' ||
      coalesce(p_entity_type,'') || '|' || coalesce(p_entity_id,'') || '|' ||
      coalesce(p_details, '{}'::jsonb)::text,
      'sha256'), 'hex');

  update audit_log set entry_hash = v_hash where seq = v_row.seq returning * into v_row;
  return v_row;
end;
$$;

-- verify_audit_chain()
create or replace function verify_audit_chain()
returns table(broken_seq bigint, reason text)
language plpgsql
as $$
declare
  r          record;
  v_prev     text := 'GENESIS';
  v_expected text;
begin
  for r in select * from audit_log order by seq asc loop
    if r.prev_hash <> v_prev then
      broken_seq := r.seq; reason := 'prev_hash mismatch'; return next; return;
    end if;

    v_expected := encode(digest(
        r.seq::text || '|' || r.prev_hash || '|' || r.actor_name || '|' || r.action || '|' ||
        coalesce(r.entity_type,'') || '|' || coalesce(r.entity_id,'') || '|' ||
        r.details::text,
        'sha256'), 'hex');

    if v_expected <> r.entry_hash then
      broken_seq := r.seq; reason := 'entry_hash mismatch'; return next; return;
    end if;

    v_prev := r.entry_hash;
  end loop;
end;
$$;

-- process_transaction()
create or replace function process_transaction(
  p_type       text,
  p_actor_id   uuid,
  p_actor_name text,
  p_items      jsonb,   -- [{"sku":"CT-COF-1234","qty":2}, ...]
  p_note       text default null
) returns jsonb
language plpgsql
security definer
as $$
declare
  v_txn_id  uuid;
  v_req     record;
  v_row     items;
  v_new_qty numeric(12,3);
  v_results jsonb := '[]'::jsonb;
begin
  if p_type not in ('checkout','restock','waste') then
    raise exception 'invalid transaction type: %', p_type;
  end if;

  if jsonb_array_length(p_items) = 0 then
    raise exception 'no items in transaction';
  end if;

  insert into transactions (type, actor_id, actor_name, note)
  values (p_type, p_actor_id, p_actor_name, p_note)
  returning id into v_txn_id;

  for v_req in
    select (e->>'sku') as sku, (e->>'qty')::numeric as qty
    from jsonb_array_elements(p_items) e
  loop
    if v_req.qty is null or v_req.qty <= 0 then
      raise exception 'invalid quantity for %', v_req.sku;
    end if;

    select * into v_row from items where sku = v_req.sku for update;
    if not found then
      raise exception 'item not found: %', v_req.sku;
    end if;

    if p_type in ('checkout','waste') then
      if v_row.quantity < v_req.qty then
        raise exception 'insufficient stock for % (have %, need %)',
          v_row.sku, v_row.quantity, v_req.qty;
      end if;
      v_new_qty := v_row.quantity - v_req.qty;
    else
      v_new_qty := v_row.quantity + v_req.qty;
    end if;

    update items
       set quantity = v_new_qty,
           version = version + 1,
           updated_at = now()
     where id = v_row.id and version = v_row.version;

    if not found then
      raise exception 'concurrent modification on % — please retry', v_row.sku;
    end if;

    insert into transaction_items
      (transaction_id, item_id, sku, item_name, quantity, qty_before, qty_after)
    values
      (v_txn_id, v_row.id, v_row.sku, v_row.name, v_req.qty, v_row.quantity, v_new_qty);

    v_results := v_results || jsonb_build_object(
      'sku', v_row.sku,
      'name', v_row.name,
      'unit', v_row.unit,
      'before', v_row.quantity,
      'after', v_new_qty
    );
  end loop;

  return jsonb_build_object(
    'transaction_id', v_txn_id,
    'type', p_type,
    'items', v_results
  );
end;
$$;

-- refresh_alerts()
create or replace function refresh_alerts()
returns void
language plpgsql
security definer
as $$
declare
  v_days int;
begin
  select coalesce(value::int, 7) into v_days from settings where key = 'expiry_warning_days';
  v_days := coalesce(v_days, 7);

  -- Escalate an open stock alert in place, before opening new ones.
  --
  -- The insert below only fires for an item with no open stock alert, so an
  -- item that drops below its threshold and then reaches zero used to keep
  -- saying "is low on stock (1 pcs left)" about an item sitting at zero. This
  -- rewrites the type and the message to match the item's current severity.
  -- The alert keeps its identity (same id, no new row), so nothing duplicates
  -- and the operator's history of it stays intact.
  update alerts a
     set type = case when i.quantity <= 0 then 'out_of_stock' else 'low_stock' end,
         message = case when i.quantity <= 0
                        then i.name || ' is out of stock'
                        else i.name || ' is low on stock (' || i.quantity || ' ' || i.unit || ' left)'
                   end
    from items i
   where i.id = a.item_id
     and a.resolved = false
     and a.type in ('low_stock','out_of_stock')
     and a.type is distinct from
         (case when i.quantity <= 0 then 'out_of_stock' else 'low_stock' end);

  -- Same for expiry: an item that crosses its date while its warning is open
  -- is expired, not merely expiring.
  update alerts a
     set type = case when i.expiration_date < current_date then 'expired' else 'near_expiry' end,
         message = case when i.expiration_date < current_date
                        then i.name || ' expired on ' || i.expiration_date
                        else i.name || ' expires on ' || i.expiration_date
                   end
    from items i
   where i.id = a.item_id
     and a.resolved = false
     and a.type in ('near_expiry','expired')
     and a.type is distinct from
         (case when i.expiration_date < current_date then 'expired' else 'near_expiry' end);

  -- open stock alerts
  insert into alerts (item_id, type, message)
  select i.id,
         case when i.quantity <= 0 then 'out_of_stock' else 'low_stock' end,
         case when i.quantity <= 0
              then i.name || ' is out of stock'
              else i.name || ' is low on stock (' || i.quantity || ' ' || i.unit || ' left)'
         end
  from items i
  where i.quantity <= i.low_stock_threshold
    and not exists (
      select 1 from alerts a
      where a.item_id = i.id and a.resolved = false
        and a.type in ('low_stock','out_of_stock')
    );

  -- open expiry alerts
  insert into alerts (item_id, type, message)
  select i.id,
         case when i.expiration_date < current_date then 'expired' else 'near_expiry' end,
         case when i.expiration_date < current_date
              then i.name || ' expired on ' || i.expiration_date
              else i.name || ' expires on ' || i.expiration_date
         end
  from items i
  where i.expiration_date is not null
    and i.expiration_date <= current_date + (v_days || ' days')::interval
    and not exists (
      select 1 from alerts a
      where a.item_id = i.id and a.resolved = false
        and a.type in ('near_expiry','expired')
    );

  -- auto-resolve stock alerts that cleared
  update alerts a
     set resolved = true, resolved_by = 'system', resolved_at = now()
   where a.resolved = false
     and a.type in ('low_stock','out_of_stock')
     and exists (
       select 1 from items i
       where i.id = a.item_id and i.quantity > i.low_stock_threshold
     );

  -- auto-resolve expiry alerts that cleared
  update alerts a
     set resolved = true, resolved_by = 'system', resolved_at = now()
   where a.resolved = false
     and a.type in ('near_expiry','expired')
     and exists (
       select 1 from items i
       where i.id = a.item_id
         and (i.expiration_date is null
              or i.expiration_date > current_date + (v_days || ' days')::interval)
     );
end;
$$;

-- ---------- after applying ----------
-- Force the current state to be recomputed so the new logic takes effect on
-- anything that is already flagged:
--
--   select refresh_alerts();
