/**
 * Extracts the re-runnable SQL from db/schema.sql into a single paste-ready file
 * for applying to a hosted Supabase project.
 *
 *   node scripts/migrate-sql.mjs
 *   npm run db:migrate
 *
 * Why this exists
 * ---------------
 * db/schema.sql is the source of truth and is written to be re-runnable in full,
 * so the simplest way to update a hosted project is to paste the whole file
 * into the Supabase SQL Editor. That works, but it means reading a few hundred
 * lines to find the one function you actually changed.
 *
 * This pulls out just the statements that are safe to run against a live
 * database and no-ops when they are already in place:
 *
 *   - `create or replace function`  — always safe, replaces the body
 *   - `alter table ... add column if not exists` — safe, existing data kept
 *
 * It deliberately EXCLUDES anything that would be destructive or that assumes a
 * brand-new project: `create extension`, `create table`, `create index`, the
 * default `insert into settings`, and the `enable row level security` block.
 * None of those are needed to pick up a function change, and leaving them out
 * means this file cannot touch a row of client data.
 *
 * It never connects to a database. It only reads schema.sql and writes a file.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const dbDir = join(here, "..", "db");

const source = readFileSync(join(dbDir, "schema.sql"), "utf8");

/** Pull a `$$ ... $$` (or `$tag$ ... $tag$`) body along with its statement. */
function functionBlock(startIndex) {
  // Find the opening dollar-quote tag that follows "create or replace function".
  // The parameter list sits between them, so the search window has to be wider
  // than a signature-length guess — scan to the end of the statement instead.
  const rest = source.slice(startIndex);
  const tag = /\$\$|\$[a-z_][a-z_0-9]*\$/i.exec(rest);
  if (!tag) return null;

  const open = tag[0];
  const openAt = startIndex + tag.index;
  const closeAt = source.indexOf(open, openAt + open.length);
  if (closeAt === -1) return null;

  const end = source.indexOf(";", closeAt);
  return {
    text: source.slice(startIndex, end + 1).trim(),
    end: end + 1,
  };
}

const functions = [];
const addColumns = [];

// Walk the file once, collecting only the two safe statement kinds.
let i = 0;
while (i < source.length) {
  const at = source.indexOf("create or replace function", i);
  const columnAt = source.indexOf("add column if not exists", i);

  if (at === -1 && columnAt === -1) break;

  // Take whichever comes first, so the scan stays in file order.
  if (at !== -1 && (columnAt === -1 || at < columnAt)) {
    const block = functionBlock(at);
    if (!block) break;
    const name = /^create or replace function\s+([a-z_0-9]+)/i.exec(block.text)?.[1];
    functions.push({ name: name ?? "unknown", text: block.text });
    i = block.end;
  } else {
    // Rewind to the start of the whole `alter table` statement.
    const lineStart = source.lastIndexOf("alter table", columnAt);
    const lineEnd = source.indexOf(";", columnAt);
    addColumns.push({
      text: source.slice(lineStart, lineEnd + 1).trim(),
    });
    i = lineEnd + 1;
  }
}

if (functions.length === 0) {
  console.error("No functions found in db/schema.sql — has its format changed?");
  process.exit(1);
}

if (addColumns.length === 0) {
  console.error("No add-column migrations found — expected the users deactivation trail.");
  process.exit(1);
}

const stamp = new Date().toISOString().slice(0, 10);

const out = `-- ============================================================
-- CafeTrack — schema updates to apply to a hosted project
-- Generated by: npm run db:migrate  (do not edit by hand)
-- Source:      db/schema.sql
-- Generated:   ${stamp}
-- ============================================================
--
-- HOW TO USE
--   Supabase dashboard -> SQL Editor -> New query -> paste this whole file
--   -> Run. It is safe to run more than once.
--
-- What this contains: only the re-runnable statements, so it cannot create,
-- drop, or modify any client data. Tables, indexes, the extension, the default
-- settings rows, and the row-level security statements are all excluded on
-- purpose — they are set up once when the project is created and are not
-- needed to pick up a change to a stored function.
--
-- Apply a structural change (a new table, column, or index) by running the
-- full db/schema.sql in the SQL Editor instead. That file is also re-runnable
-- and never drops or truncates anything.
--

-- ---------- columns added since the first release ----------
-- Safe on a live database: the column is added only if it is not already there,
-- and existing rows are left untouched.
${addColumns.map((a) => a.text).join("\n")}

-- ---------- stored functions ----------
-- create or replace keeps the existing function id and re-points it at the new
-- body, so anything already calling it keeps working.
${functions
  .map((f) => `-- ${f.name}()\n${f.text}`)
  .join("\n\n")}

-- ---------- after applying ----------
-- Force the current state to be recomputed so the new logic takes effect on
-- anything that is already flagged:
--
--   select refresh_alerts();
`;

const target = join(dbDir, "migrate.sql");
writeFileSync(target, out, "utf8");

console.log(`Wrote db/migrate.sql\n`);
console.log(`  ${addColumns.length} column migration(s)`);
console.log(`  ${functions.length} function(s): ${functions.map((f) => f.name).join(", ")}`);
console.log(`\nPaste it into the Supabase SQL Editor and run.`);
